.MODEL SMALL
.STACK 100H
.DATA
    CR EQU 0DH   ; CARRAIGE RETURN (START OF NEW LINE)
    LF EQU 0AH   ; LINE FEED (NEW LINE) 
    
MSG1 DB 'ENTER A LOWER CASE LETTER: $'
MSG2 DB 0DH,0AH,'IN UPPER CASE IT IS: '
CHAR DB ?,'$'
.CODE
MAIN PROC
    ;INITIALIZE DS
    MOV AX,@DATA;GET DATA SEGMENT
    MOV DS,AX;INTIALIZE DS
    ;PRINT USER PROMPT
    LEA DX,MSG1 ;GET DATA SEGMENT
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21H     ;DISPLAY FIRST MESSAGE
    
    ;INPUT A CHARACTER AND CONVERT TO UPPER CASE
    MOV AH,1    ;READ CHARACTER FUNCTION 
    INT 21H     ;READ A SMALL LETTER INTO AL
    SUB AL,20H  ;CONVERT IT TO UPPER CASE
    MOV CHAR,AL ;AND STORE IT
    ;DISPLAY ON THE NEXT LINE
    
    LEA DX,MSG2 ;GET SECOND MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21H
    ;DOS EXIT
    
    MOV AH,4CH
    INT 21H     ;DOS EXIT
    MAIN ENDP
         END MAIN