.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC
    ;DISPLAY PROMPT
    MOV AH,2   ; DISPLAY CHARACTER FUNCTION
    MOV DL,'?' ; CHARACTER IS '?'
    INT 21H   ;DISPLAY IT
    ;IMPUT A CHARACTER
    
    MOV AH,1 ;READ CHARACTER FUNCTION
    MOV BL,AL;SAVE IT IN BL
    ;GO TO A NEW LINE
    
    MOV AH,2  ;DISPLAY CHARACTER FUNCTION
    MOV DL,0DH;CARRIAGE RETURN
    INT 21H   ;EXECUTE LINE FEED
    ;DISPLAY CHARACTER
    MOV DL,BL ; RETRIEVE CHARACTER
    INT 21H   ;AND DISPLAY IT
    
    ;RETURN TO DOS
    MOV AH, 4CH ;DOS EXIT FUNCTION
    INT 21H     ;EXIT TO DOS
    MAIN ENDP
         END MAIN